version: 0.0
os: linux
file_exists_behavior: OVERWRITE
files:
  - source: .
    destination: /home/ubuntu/cs3219-task-b-link-renderer
hooks:
  ApplicationStart:
    - location: scripts/backend/start_backend.sh
      timeout: 360
      runas: root
