version: '3.9'

services:
  mongodb-local:
    container_name: "mongodb-local"
    image: mongo
    ports:
      - "27017:27017"

  backend:
    container_name: "backend"
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb-local
    environment:
      - ENV=DEV
      - HOST=0.0.0.0
      - PORT=8000
      - MONGODB_CLOUD_URI=
      - MONGODB_LOCAL_URI=mongodb://mongodb:27017/
      - FRONTEND_HOST=http://frontend:3000
      - JWT_SECRET=token

